spring.application.name=musicrm
 spring.datasource.url=jdbc:mysql://localhost:3306/musicrm
 spring.datasource.username=root
 spring.datasource.password=cybshoushou66
 spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 spring.jpa.database=mysql
 spring.jpa.hibernate.ddl-auto=update
 spring.jpa.show-sql=true
